### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by antoniodecastroalves** [antoniodecastroalves/netflix-clone-dio#1]
Project divided into 9 parts

- [x] First part - Visual Studio Code and Extensions
- [x] Second part - HTML and directory structures
- [x] Third part - CSS3 and Flexbox
- [x] Fourth part - CSS3 and Flexbox 
- [x] Fifth part - Continuation CSS3 and Flexbox 
- [x] Sixth part - Flexbox 
- [x] Seventh part - HTML and Plugin Owl Carousel 2
- [x] Eighth part - Using Media Queries
- [x] Ninth part - Finalizing project

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
First part - Visual Studio Code and Extensions , Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Second part - HTML and directory structures , Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Third part - CSS3 and Flexbox, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Fourth part - CSS3 and Flexbox, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Fifth part - Continuation CSS3 and Flexbox, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Sixth part - Flexbox, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Seventh part - HTML and Plugin Owl Carousel 2, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Eighth part - Using Media Queries, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Ninth part - Finalizing project, Finished!
